package apt

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// RepoEntry is one .deb already present in the bundle.
type RepoEntry struct {
	RelPath string // bundle relative, e.g. apt/pool/n/nginx/nginx_1.24_amd64.deb
	SHA256  string
	Size    int64
}

// GenerateRepo writes apt metadata next to the pool so the mirror can be used
// directly, without Nexus:
//
//	deb [trusted=yes] file:///srv/airgap-mirror/apt stable main
//
// The control stanza is read back from each .deb, so the generated index
// carries the same fields apt would normally see.
func GenerateRepo(bundleRoot, arch string, entries []RepoEntry) error {
	sort.Slice(entries, func(i, j int) bool { return entries[i].RelPath < entries[j].RelPath })

	var buf bytes.Buffer
	for _, e := range entries {
		abs := filepath.Join(bundleRoot, filepath.FromSlash(e.RelPath))
		control, err := ControlOf(abs)
		if err != nil {
			return fmt.Errorf("gen-repo: %w", err)
		}
		filename := strings.TrimPrefix(e.RelPath, "apt/")
		buf.WriteString(dropFields(control, "Filename", "Size", "SHA256", "MD5sum", "SHA1"))
		fmt.Fprintf(&buf, "\nFilename: %s\nSize: %d\nSHA256: %s\n\n", filename, e.Size, e.SHA256)
	}

	dir := filepath.Join(bundleRoot, "apt", "dists", "stable", "main", "binary-"+arch)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	plain := buf.Bytes()
	if err := os.WriteFile(filepath.Join(dir, "Packages"), plain, 0o644); err != nil {
		return err
	}
	var gz bytes.Buffer
	zw := gzip.NewWriter(&gz)
	if _, err := zw.Write(plain); err != nil {
		return err
	}
	if err := zw.Close(); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "Packages.gz"), gz.Bytes(), 0o644); err != nil {
		return err
	}

	rel := &bytes.Buffer{}
	fmt.Fprintf(rel, "Origin: airgapkit\nLabel: airgap-mirror\nSuite: stable\nCodename: stable\nArchitectures: %s\nComponents: main\nDescription: Offline mirror generated by airgapkit\nDate: %s\nSHA256:\n",
		arch, time.Now().UTC().Format(time.RFC1123))
	for _, name := range []string{"Packages", "Packages.gz"} {
		body, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return err
		}
		sum := sha256.Sum256(body)
		fmt.Fprintf(rel, " %s %d main/binary-%s/%s\n", hex.EncodeToString(sum[:]), len(body), arch, name)
	}
	return os.WriteFile(filepath.Join(bundleRoot, "apt", "dists", "stable", "Release"), rel.Bytes(), 0o644)
}

// dropFields removes fields we regenerate, keeping folded continuation lines
// attached to the field they belong to.
func dropFields(control string, drop ...string) string {
	skip := map[string]bool{}
	for _, d := range drop {
		skip[strings.ToLower(d)] = true
	}
	var out []string
	dropping := false
	for _, line := range strings.Split(control, "\n") {
		if line == "" {
			continue
		}
		if line[0] == ' ' || line[0] == '\t' {
			if !dropping {
				out = append(out, line)
			}
			continue
		}
		key, _, _ := strings.Cut(line, ":")
		dropping = skip[strings.ToLower(strings.TrimSpace(key))]
		if !dropping {
			out = append(out, line)
		}
	}
	return strings.Join(out, "\n")
}
